
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef KEYBOARD_DICT_H
#define KEYBOARD_DICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 _valueRangeTest (UNS8 typeValue, void * value);
const indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data _Data;
extern UNS32 Buttons_State[2];		/* Mapped at index 0x2000, subindex 0x01 - 0x02 */
extern UNS32 Leds_State[2];		/* Mapped at index 0x2001, subindex 0x01 - 0x02 */
extern UNS8 Leds_ON;		/* Mapped at index 0x2002, subindex 0x00*/

#endif // KEYBOARD_DICT_H
