
/* File generated by gen_cfile.py. Should not be modified. */

#include "Keyboard_dict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 Buttons_State[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS32 Leds_State[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 Leds_ON = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 _valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 _bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 _iam_a_slave = 1;

TIMER_HANDLE _heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 _obj1000 = 0x30191;	/* 197009 */
                    subindex _Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 _obj1001 = 0x0;	/* 0 */
                    subindex _Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 _highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 _obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t _Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex _Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 _obj1005 = 0x80;	/* 128 */
                    ODCallback_t _Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 _obj1006 = 0x0;	/* 0 */
                    ODCallback_t _Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1006 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 _obj1008[10] = "Keyboard";
                    subindex _Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&_obj1008 }
                     };

/* index 0x100C :   Guard Time. */
                    UNS16 _obj100C = 0x0;	/* 0 */
                    subindex _Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&_obj100C }
                     };

/* index 0x100D :   Life Time Factor */ 
                    UNS8 _obj100D = 0x0;   /* 0 */

/* index 0x1010 :   Store parameters. */
                    UNS8 _highestSubIndex_obj1010 = 4; /* number of subindex - 1*/
                    UNS32 _obj1010_Save_All_Parameters = 0x1;	/* 1 */
                    UNS32 _obj1010_Save_Communication_Parameters = 0x1;	/* 1 */
                    UNS32 _obj1010_Save_Application_Parameters = 0x1;	/* 1 */
                    UNS32 _obj1010_Save_Manufacturer_Parameters_1 = 0x1;	/* 1 */
                    subindex _Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1010_Save_All_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1010_Save_Communication_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1010_Save_Application_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1010_Save_Manufacturer_Parameters_1 }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 _highestSubIndex_obj1011 = 4; /* number of subindex - 1*/
                    UNS32 _obj1011_Restore_All_Default_Parameters = 0x1;	/* 1 */
                    UNS32 _obj1011_Restore_Communication_Default_Parameters = 0x1;	/* 1 */
                    UNS32 _obj1011_Restore_Application_Default_Parameters = 0x1;	/* 1 */
                    UNS32 _obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 = 0x1;	/* 1 */
                    subindex _Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1011_Restore_All_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1011_Restore_Communication_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1011_Restore_Application_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 }
                     };

/* index 0x1012 :   TIME COB ID. */
                    UNS32 _obj1012 = 0x100;	/* 256 */
                    subindex _Index1012[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1012 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 _obj1014 = 0x80;	/* 128 */
                    subindex _Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 _highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 _obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex _Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 _obj1017 = 0x2710;	/* 10000 */
                    ODCallback_t _Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 _highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 _obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 _obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 _obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 _obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex _Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 _highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 _obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 _obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex _Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 _highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 _obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 _obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 _obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t _Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 _highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 _obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 _obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 _obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t _Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 _highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 _obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 _obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 _obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t _Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 _highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 _obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 _obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 _obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t _Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 _highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 _obj1A00[] = 
                    {
                      0x20000120,	/* 536871200 */
                      0x20000220	/* 536871456 */
                    };
                    ODCallback_t _Index1A00_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[1] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 _highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 _obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[1] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 _highestSubIndex_obj1A02 = 2; /* number of subindex - 1*/
                    UNS32 _obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex _Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[1] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 _highestSubIndex_obj1A03 = 1; /* number of subindex - 1*/
                    UNS32 _obj1A03[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex _Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[0] }
                     };

/* index 0x2000 :   Mapped variable Buttons_State */
                    UNS8 _highestSubIndex_obj2000 = 2; /* number of subindex - 1*/
                    subindex _Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj2000 },
                       { RO, uint32, sizeof (UNS32), (void*)&Buttons_State[0] },
                       { RO, uint32, sizeof (UNS32), (void*)&Buttons_State[1] }
                     };

/* index 0x2001 :   Mapped variable Leds_State */
                    UNS8 _highestSubIndex_obj2001 = 2; /* number of subindex - 1*/
                    subindex _Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj2001 },
                       { RW, uint32, sizeof (UNS32), (void*)&Leds_State[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Leds_State[1] }
                     };

/* index 0x2002 :   Mapped variable Leds_ON */
                    ODCallback_t Leds_ON_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index2002[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Leds_ON }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable _objdict[] = 
{
  { (subindex*)_Index1000,sizeof(_Index1000)/sizeof(_Index1000[0]), 0x1000},
  { (subindex*)_Index1001,sizeof(_Index1001)/sizeof(_Index1001[0]), 0x1001},
  { (subindex*)_Index1003,sizeof(_Index1003)/sizeof(_Index1003[0]), 0x1003},
  { (subindex*)_Index1005,sizeof(_Index1005)/sizeof(_Index1005[0]), 0x1005},
  { (subindex*)_Index1006,sizeof(_Index1006)/sizeof(_Index1006[0]), 0x1006},
  { (subindex*)_Index1008,sizeof(_Index1008)/sizeof(_Index1008[0]), 0x1008},
  { (subindex*)_Index100C,sizeof(_Index100C)/sizeof(_Index100C[0]), 0x100C},
  { (subindex*)_Index1010,sizeof(_Index1010)/sizeof(_Index1010[0]), 0x1010},
  { (subindex*)_Index1011,sizeof(_Index1011)/sizeof(_Index1011[0]), 0x1011},
  { (subindex*)_Index1012,sizeof(_Index1012)/sizeof(_Index1012[0]), 0x1012},
  { (subindex*)_Index1014,sizeof(_Index1014)/sizeof(_Index1014[0]), 0x1014},
  { (subindex*)_Index1016,sizeof(_Index1016)/sizeof(_Index1016[0]), 0x1016},
  { (subindex*)_Index1017,sizeof(_Index1017)/sizeof(_Index1017[0]), 0x1017},
  { (subindex*)_Index1018,sizeof(_Index1018)/sizeof(_Index1018[0]), 0x1018},
  { (subindex*)_Index1200,sizeof(_Index1200)/sizeof(_Index1200[0]), 0x1200},
  { (subindex*)_Index1800,sizeof(_Index1800)/sizeof(_Index1800[0]), 0x1800},
  { (subindex*)_Index1801,sizeof(_Index1801)/sizeof(_Index1801[0]), 0x1801},
  { (subindex*)_Index1802,sizeof(_Index1802)/sizeof(_Index1802[0]), 0x1802},
  { (subindex*)_Index1803,sizeof(_Index1803)/sizeof(_Index1803[0]), 0x1803},
  { (subindex*)_Index1A00,sizeof(_Index1A00)/sizeof(_Index1A00[0]), 0x1A00},
  { (subindex*)_Index1A01,sizeof(_Index1A01)/sizeof(_Index1A01[0]), 0x1A01},
  { (subindex*)_Index1A02,sizeof(_Index1A02)/sizeof(_Index1A02[0]), 0x1A02},
  { (subindex*)_Index1A03,sizeof(_Index1A03)/sizeof(_Index1A03[0]), 0x1A03},
  { (subindex*)_Index2000,sizeof(_Index2000)/sizeof(_Index2000[0]), 0x2000},
  { (subindex*)_Index2001,sizeof(_Index2001)/sizeof(_Index2001[0]), 0x2001},
  { (subindex*)_Index2002,sizeof(_Index2002)/sizeof(_Index2002[0]), 0x2002},
};

const indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1003: i = 2;*callbacks = _Index1003_callbacks; break;
		case 0x1005: i = 3;*callbacks = _Index1005_callbacks; break;
		case 0x1006: i = 4;*callbacks = _Index1006_callbacks; break;
		case 0x1008: i = 5;break;
		case 0x100C: i = 6;break;
		case 0x1010: i = 7;break;
		case 0x1011: i = 8;break;
		case 0x1012: i = 9;break;
		case 0x1014: i = 10;break;
		case 0x1016: i = 11;break;
		case 0x1017: i = 12;*callbacks = _Index1017_callbacks; break;
		case 0x1018: i = 13;break;
		case 0x1200: i = 14;break;
		case 0x1800: i = 15;*callbacks = _Index1800_callbacks; break;
		case 0x1801: i = 16;*callbacks = _Index1801_callbacks; break;
		case 0x1802: i = 17;*callbacks = _Index1802_callbacks; break;
		case 0x1803: i = 18;*callbacks = _Index1803_callbacks; break;
		case 0x1A00: i = 19;*callbacks = _Index1A00_callbacks; break;
		case 0x1A01: i = 20;break;
		case 0x1A02: i = 21;break;
		case 0x1A03: i = 22;break;
		case 0x2000: i = 23;break;
		case 0x2001: i = 24;break;
		case 0x2002: i = 25;*callbacks = Leds_ON_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status _PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index _firstIndex = {
  14, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  15, /* PDO_TRS */
  19 /* PDO_TRS_MAP */
};

const quick_index _lastIndex = {
  14, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  18, /* PDO_TRS */
  22 /* PDO_TRS_MAP */
};

const UNS16 _ObjdictSize = sizeof(_objdict)/sizeof(_objdict[0]); 

CO_Data _Data = CANOPEN_NODE_DATA_INITIALIZER();

